---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull premsai1503/miniproj

    - name: running container
      shell: docker run -it -d premsai1503/miniproj /bin/bash